depends_on:
  - docker

pipeline:

# clone dependencies

  clone-marathon-utils:
    image: woodpeckerci/plugin-git
    group: clone
    settings:
      remote: https://github.com/Hopper262/marathon-utils
      sha: e297f264f4da2e7283adcb120ffadca9720c84d6
      ref: e297f264f4da2e7283adcb120ffadca9720c84d6
      path: marathon-utils

  clone-classic-mac-utils:
    image: woodpeckerci/plugin-git
    group: clone
    settings:
      remote: https://github.com/Hopper262/classic-mac-utils
      sha: cfa801ec4b4611b2fc9460f1c45eb10bf0c79586
      ref: cfa801ec4b4611b2fc9460f1c45eb10bf0c79586
      path: classic-mac-utils

# clone maps

  clone-m1:
    image: woodpeckerci/plugin-git
    group: clone
    settings:
      remote: https://github.com/Aleph-One-Marathon/data-marathon
      sha: 75f194c3a03e60597f04c887a5d07165ad1c2b0e
      ref: 75f194c3a03e60597f04c887a5d07165ad1c2b0e
      path: data/m1

  clone-m2:
    image: woodpeckerci/plugin-git
    group: clone
    settings:
      remote: https://github.com/Aleph-One-Marathon/data-marathon-2
      sha: 0c5dcb94003936111dcae1420f782abfb7c3b1fd
      ref: 0c5dcb94003936111dcae1420f782abfb7c3b1fd
      path: data/m2

  clone-m3:
    image: woodpeckerci/plugin-git
    group: clone
    settings:
      remote: https://github.com/Aleph-One-Marathon/data-marathon-infinity
      sha: 95045260f343bb700bddb557515617ba578a464e
      ref: 95045260f343bb700bddb557515617ba578a464e
      path: data/m3

# convert to XML

  map2xml-m1:
    image: ${REGISTRY_HOST}/arno/marathon-perl:latest
    pull: true
    group: xml
    commands:
      - classic-mac-utils/macbin2data.pl < data/m1/Map.scen > data/m1.map
      - marathon-utils/map2xml.pl < data/m1.map > data/m1-map.xml

  map2xml-m2:
    image: ${REGISTRY_HOST}/arno/marathon-perl:latest
    pull: true
    group: xml
    commands:
      - classic-mac-utils/macbin2data.pl < data/m2/Map.sceA > data/m2.map
      - marathon-utils/map2xml.pl < data/m2.map > data/m2-map.xml

  map2xml-m3:
    image: ${REGISTRY_HOST}/arno/marathon-perl:latest
    pull: true
    group: xml
    commands:
      - classic-mac-utils/macbin2data.pl < data/m3/Map.sceA > data/m3.map
      - marathon-utils/map2xml.pl < data/m3.map > data/m3-map.xml

# convert to SVG

  xml2svg-m1:
    image: ${REGISTRY_HOST}/arno/marathon-python:latest
    pull: true
    group: svg
    commands:
      - mkdir -p output
      - ./map2svg.py -d output/m1 -m data/m1-map.xml -i marathon-utils/map-extras/M1_ignored_polys.txt

  xml2svg-m2:
    image: ${REGISTRY_HOST}/arno/marathon-python:latest
    pull: true
    group: svg
    commands:
      - mkdir -p output
      - ./map2svg.py -d output/m2 -m data/m2-map.xml -i marathon-utils/map-extras/M2_ignored_polys.txt

  xml2svg-m3:
    image: ${REGISTRY_HOST}/arno/marathon-python:latest
    pull: true
    group: svg
    commands:
      - mkdir -p output
      - ./map2svg.py -d output/m3 -m data/m3-map.xml -i marathon-utils/map-extras/M3_ignored_polys.txt

# deploy

  rsync:
    image: drillster/drone-rsync
    settings:
      hosts: bottle.fracas.net
      source: ./output/
      target: ~/svg-marathon/
      user: arno
      key:
        from_secret: rsync_key
      secrets: [ rsync_key ]
